server:
  port: 7001




eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false   #是否向eureka服务中心注册自己
    fetch-registry: false
