server:
  port: 8001


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: root

  application:
    name: springcloud-provider-dept

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/xml/*.xml


eureka:
  instance:
    instance-id: provider-dept
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

info:
  app.name: springcloud-provider-dept
  company.name: www.yuxin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

